### ISSUE TITLE
cannot edit or see code in client app

### ISSUE THREAD

**Issue by xnopasaranx** [superpowers/superpowers-love2d#7]
Hi there, I am having a weird issue.
I have installed the latest server from git. I can successfully install love2d as a system and if I connect to the server through the browser UI, everything seems to be in order. However when I build the client app from github source (1.0 prerelease) and then connect to the server, I cannot open any lua scriptfiles. I can see the assets in the tree view but no code appears in the editor and I am unable to create new assets of script files.

**Comment by elisee** [comment]
Hi!

Lua code editing seems to work fine for me:

![image](https://cloud.githubusercontent.com/assets/446986/16499207/a2d33498-3eff-11e6-9992-fcc8dfa16429.png)

Are you using the latest sources everywhere? Make sure the sub-repositories are up-to-date too and try rebuilding everything, maybe.

Note that right now, the latest version of Superpowers LÖVE don't support running your game because we just merged the new build system and still need to update Superpowers LÖVE accordingly.

EDIT: Running LÖVE games is now supported again in latest master branch.

**Comment by xnopasaranx** [comment]
Thanks for the quick answer. Yes, I believe I am using the latest sources, but belief isn't really a constant here, so I will check again. Maybe I cloned the wrong repository for the client. I know that I won't be able to do a lot, but am excited for the new features. So I am eager to try things out and report any issues I find.

EDIT: Okay, I have deleted my work folder and cloned the repo again using --depth=1 to make sure. I built version 0.23.0 of the client.

As I said, the web-ui works and I can edit code there. The problem I am having seems to be related to the client app, so I might be reporting the issue at the wrong place.

**Comment by elisee** [comment]
Do you get any error in the app console? You can open it with F12.

**Comment by bilou84** [comment]
Hmm, looks like you are building the client app.
But then you are using the pre-compiled version of the core and the lua systems through the app. These aren't up to date either and you need to compile them from source as well for now.
See instructions here http://docs.superpowers-html5.com/fr/developpement/building-superpowers

**Comment by xnopasaranx** [comment]
Ah! Alright thanks, I did compile all on their own but thought I wouldn't
need that if I was building the client.
